### ISSUE TITLE
Randomize tagv creation

### ISSUE THREAD

**Issue by barnjamin** [OpenTSDB/opentsdb#1046]
Is there a particular reason tagvs don't have a config option to randomize UID assignment like metrics do?

https://github.com/OpenTSDB/opentsdb/blob/master/src/core/TSDB.java#L213

**Comment by manolama** [comment]
Yup. Due to the way we write the row keys, metrics come first (or a salt if enabled). This means the distribution across the sorted logical HBase hash table depends on the first bytes of the key. Randomizing the metric means the distribution will be spread nicely amongst the regions and region servers.

Since the tag values come later in the row key, they have little effect on the distribution. And since they're generally shared amongst metrics and assigned in a somewhat random order, there's no need to randomize them. Additionally tag values are often assigned so we want to avoid the collisions and latency associated with random assignment.

Hope that makes sense :)

**Comment by IDerr** [comment]
Hi, @barnjamin if your question has been answered, could you please close this issue?

Thanks :)

**Comment by barnjamin** [comment]
Yep, sorry about that.
