### ISSUE TITLE
what aggregator means in /api/query

### ISSUE THREAD

**Issue by nch14** [OpenTSDB/opentsdb#1124]
Since there is an option param downsample that reduce the amount of data returned
So what does required param aggregator  use for ? to show additional summary?
Willing to get your help.
Thanks !

**Comment by johann8384** [comment]
in OpenTSDB aggregation aggregates results across series.

Example metric:

```
cpu.free host=hostA datacenter=datacenterA
cpu.free host=hostB datacenter=datacenterA
cpu.free host=hostC datacenter=datacenterB
cpu.free host=hostD datacenter=datacenterB
```

So, if you queries for cpu.free, and datacenter=*, you would get back 2 series:

```
cpu.free datacenter=datacenterA
cpu.free datacenter=datacenterB
```

The aggregator would apply the aggregation function to the host tag and it would not be individually reported in the series.

This is why it is important to consider how you structure your metrics and what you include in the name vs a tag.

In a Graphite system, you might have this:

```
datacenterA.hostA.cpu.free
datacenterB.hostB.cpu.free
datacenterC.hostC.cpu.free
datacenterD.hostD.cpu.free
```


In OpenTSDB you could have:

```
datacenterA.cpu.free host=hostA
datacenterA.cpu.free host=hostB
datacenterB.cpu.free host=hostC
datacenterB.cpu.free host=hostD

```
but you would not be able to aggregate out the datacenter because it is not in a tag. 

So the preferred/best way to store it in OpenTSDB is the first method:

```
cpu.free host=hostA datacenter=datacenterA
cpu.free host=hostB datacenter=datacenterA
cpu.free host=hostC datacenter=datacenterB
cpu.free host=hostD datacenter=datacenterB
```

**Comment by nch14** [comment]
Thanks a lot
