### ISSUE TITLE
Why opentsdb only create one tsdb table for time series?

### ISSUE THREAD

**Issue by LostLegend** [OpenTSDB/opentsdb#1602]
If i want to manage several metrics in different tables, it is not support. i wonder why it design as such.

**Comment by muffix** [comment]
Since OpenTSDB 2.4, it does support rolled-up and pre-aggregated data in different resolutions in separate tables. 
What would be your use case for splitting raw data across multiple tables? HBase is designed as a sorted multidimensional map and with OpenTSDB's choice of row keys already makes sure that data points of the same name are stored closely together.

**Comment by LostLegend** [comment]
Thanks for your answer. I mean if i want to manage different data in different business scene for operation. Only one table is not friendly for operation and management. Although the same name data are stored closely, query is not my only target.

**Comment by muffix** [comment]
You can run a separate OpenTSDB instance and configure the names for the tables separately. There are four tables you'll need to define:
- tsd.storage.hbase.data_table
- tsd.storage.hbase.meta_table
- tsd.storage.hbase.tree_table
- tsd.storage.hbase.uid_table

http://opentsdb.net/docs/build/html/user_guide/configuration.html
