### ISSUE TITLE
Put same data with different value, I find there are tow records in hbase. It's a bug?

### ISSUE THREAD

**Issue by zuzeep** [OpenTSDB/opentsdb#1858]
ex: there two records :  

- a. metric/tagk=tagv/timestamp/1
- b. metric/tagk=tagv/timestamp/1.01

then I put a and b into opentsdb (a is first and b is second). 
And i find one key with different qulitifier in hbase. Record b doesn't override record a!
When I query , opentsdb awayls return a. Because query code filter record b.
How can i put b override a ?

**Comment by pengmq1** [comment]
I think because of the different type of value, 1 is short in opentsdb, 1.01 is float. So the qulitfiers are different,  these two datapoint use two column.  Opentsdb does not check same records timestamp. You can use /api/query to delete a. Refer to http://opentsdb.net/docs/build/html/api_http/query/index.html

**Comment by qiguoxiaosheng** [comment]
2.4.0-release version,  opentsdb always return the newest record when query and there was only the latest record left in hbase after datapoints merged.

**Comment by manolama** [comment]
@pengmq1 is correct.
