### ISSUE TITLE
a question of the `fitsInFloat` method

### ISSUE THREAD

**Issue by qiguoxiaosheng** [OpenTSDB/opentsdb#1988]
https://github.com/OpenTSDB/opentsdb/blob/12bc21ddcc3d559c8d1ca696906888a88d056876/src/core/Tags.java#L857
The data type float and double store same value for x.0, x.5 but it stores different values for x.1, x.2, x.3, x.4, x.6, x.7, x.8, and x.9. 
Can we use `return value.equals(Float.toString((float) d));` instead `return ((float) d) == d;` ?

**Comment by manolama** [comment]
Hi! That's why the current equality test errs on the side of caution by leaving a value like `1.123` as a double instead of truncating it to a float even though the string version would be fine in a float. The `Float.toString()` method will round the value and print with scientific notation, thus losing precision so we could have a lot of errors on larger values. 

It _would_ be good to have a setting that would truncate improper fractions as, really, who needs 8 bytes of `1.66666....`?
