### ISSUE TITLE
how can I delete a metric.

### ISSUE THREAD

**Issue by hanbaga** [OpenTSDB/opentsdb#337]
I want to delete some metrics which were created by some guy.  I can't find any a cli or some function to do it. who can help me to resolve the issue.

**Comment by gsaray101** [comment]
I have installed OpenTSDB version 2.1.0 when I issue command like this:
tsdb scan 2014/05/01 sum <metric-name> tag_name1=tag_value1 tag_name1=tag_value1 --delete

I still see the metric in the uid table. Any ideas what might be going on here?

**Comment by nickman** [comment]
@gsaray101;

Since you deleted all the timeseries with that metric, possibly issuing a 
`tsdb uid fsck fix delete_unknown`
should delete the unused UIDs no ?

**Comment by vyshaliN** [comment]
@manolama 
The code under pull request 291 seems to be promising for deletion.Hope that has been merged with master.
I have tsdb and hbase hosted in Azure.I'm tunneling the tsdb to my local machine so that I could view the tsdb UI at localhost:4242
Please suggest me on the input parameters which I'm giving,
tsd.network.bind=0.0.0.0
tsd.network.port=4242(tunneled-port)
tsd.storage.hbase.data_table=wasb://<container-name>@<hbase-name>.blob.core.windows.net/hbase/data/default/tsdb
tsd.storage.hbase.meta_table=wasb://<container-name>@<hbase-name>.blob.core.windows.net/hbase/data/default/tsdb-meta
tsd.storage.hbase.uid_table=wasb://<container-name>@<hbase-name>.blob.core.windows.net/hbase/data/default/ts-uid
tsd.storage.hbase.zk_basedir=/usr/local/zookeeper (This would be the local path in hbase cluster)
tsd.storage.hbase.zk_quorum=localhost
tsd.logback.file=C:\\Users\\h156767\\Documents\\Analytics\\GDPR\\sample.log

Correct me if I'm wrong.

Regards
Vyshali

**Comment by johann8384** [comment]
Vyshali, it was merged 4 years ago according to the PR.

**Comment by vyshaliN** [comment]
Please comment on my input parameters

**Comment by vyshaliN** [comment]
I add the following dependency,

<dependency>
	    <groupId>net.opentsdb</groupId>
	    <artifactId>opentsdb</artifactId>
	    <version>2.2.0</version>
</dependency>

The following imports worked fine
import net.opentsdb.tools.ArgP;
import net.opentsdb.tools.BuildData;

There was no UidManager class,CliOptions class,CliUtils class.So I added manually these classes to my application.Can I proceed this way?

Please suggest me solutions.

Regards
Vyshali

**Comment by johann8384** [comment]
Off the too of my head, I really don't know, I haven't tried to delete any
data programmatically. I use the CLI.

Just try it and let us know if it works. You can run a local tsdb and
standalone HBase to develop the solution.

**Comment by vyshaliN** [comment]
I want to know the exact function of tsdb library which does the delete operation without using cli or api.
That would be really helpful if you can share.
