### ISSUE TITLE
fsck printing lots of "Our qualifier was in the delete list!!!" 

### ISSUE THREAD

**Issue by vitorboschi** [OpenTSDB/opentsdb#436]
As the title says, it happens quite frequently when I run fsck here. I'm not sure if it's related, but at the end summary, there's a summary saying I have some dupes, and all are correctable, however, it doesn't correct them, despite me using --fix-duplicates or --fix-all

this may be related to issue #430

**Comment by kylemallory** [comment]
I'm seeing the same issue.  I am also experiencing an issue that I'm trying to troubleshoot, where a particular set of metrics are not showing up in the database.  I don't know if there is any relation, but...

Last week, I decided to flush all my existing data and start over again (I'm still solidifying my metric/tag structure, etc).  After shutting everything down, dropping the 4 tables, recreating the schema, and then restarting everything again, a handful of metrics are not coming into the database; specifically any metric which BEGINS with the name "haproxy" (ie, haproxy.stot, haproxy.bin, etc).  There could be more, but so far I've only noticed this case).  I can see the metrics push across the wire, and reach tsdb (from tcollector), I have auto-create uids, and other related features enabled, but the metric never gets created.  More confusing, there is no errors, warnings, or otherwise from tsdb about why the data might have been rejected.

In troubleshooting this, I decided to "fix" the database, despite having just purged all the data 3 days earlier.

The fix has been running for more than an hour. I'd guess that 97% of all the messages in the output of the fsck command, are "Our qualifier was in the delete list!!!"

I would like, at the very least, to understand what this message means so I can determine whether its relevant to my problem or not.

**Comment by shaneodonnell** [comment]
Same behavior here.  Running 2.1.0 RC1.

**Comment by kylemallory** [comment]
Ignore my issue above... it was not related to this issue; I had a metric with more than 8 tags...

**Comment by oozie** [comment]
Hey folks - if you still experience this, could someone please supply fsck output?

**Comment by vitorboschi** [comment]
I have started a new database, and since that, I've got no dups yet. I'll report back when/if I manage to reproduce it again

**Comment by manolama** [comment]
Try out the latest "next" branch please. I pulled in some tweaks from @oozie that may help with this.

**Comment by manolama** [comment]
*bump* Try RC2 please and let me know if ya'll still see the warnings. Thanks!

**Comment by tkrajca** [comment]
Hi, I see the warning in RC1, RC2, head of 'next' and head of 'put'. I attached output of 

./build/tsdb fsck --fix-all 1 sum operational.australia.nem.ec.meter.reactive_power

when run against RC2 (IP addresses and hostnames in the log are replace with xx.xx.xxx.xx) here http://filebin.net/005t3a53nu.

I am not able to get rid of the fsck issues not matter what I try - --resolve-duplicates, --last-write-wins, ...

Cheers,
Tomas

**Comment by manolama** [comment]
Thanks, taking a look now.

**Comment by manolama** [comment]
@tkrajca Would it be possible for you to run it with Debug enabled and dump that output please?

**Comment by manolama** [comment]
@tkrajca Actually try this patch please: https://github.com/manolama/opentsdb/tree/next_fsck_fix
I tried a test with the compacted columns I saw in your log and they functioned, sorta, correctly in that they took the oldest and deleted the newest column but didn't merge them. I'll work on some code for that.

**Comment by manolama** [comment]
OK folks, try out the tip of ``next`` please and run with DEBUG logging. It looks like it was doing the right thing with two or more compacted columns but now we'll capture the qualifiers and values to make sure. Thanks!

**Comment by tkrajca** [comment]
Hi @manolama and thanks for looking into this.

Sorry, should have put it into debug originally, there is a new log file http://filebin.net/2zgmeo0siu/opentsdb.log run against 12ca959376627c361181e8a01671bd7ff7af9a4b (the head of next) in debug.

Cheers,
Tomas

**Comment by manolama** [comment]
Got it. A regular, happily compacted column would trigger that "Qualifier was in the delete list!!!" message even though nothing was wrong. Fixed the logic in 34fc5fe0e7bdd8e6665381bd4465043ab8b85502.
If there's still an issue with fsck, open another PR please with some logs.
Thanks for your help everyone!
