### ISSUE TITLE
Make MAX_NUM_TAGS Configurable; Throw error when attempting to write data when tags excceds MAX_NUM_TAGS.

### ISSUE THREAD

**Issue by kylemallory** [OpenTSDB/opentsdb#437]
First, there needs to be some kind of error or other indication when attempting to write a metric with more than 8 tags.  Currently (based on my log level), tsdb quietly drops the metric, and I'm left wondering why my metric isn't showing up in the database.

Secondly, could MAX_NUM_TAGS become a configurable/tunable item?  I have a few metrics which are pushing the tag limit.  I understand the performance reasons/concerns associated with changing this, but would rather not have to recompile/deploy everytime I tweak this value.

**Comment by manolama** [comment]
I'll double check but it *should* respond to the sender that there were too many tags. Are you writing over the Telnet style interface? If so, check your receive buffer for errors. Those aren't logged right now because it can potentially fill up the disk if there are a lot of data points coming back with bad values.

And yeah, this can easily become a config value so we'll get that in (or if you have time to work on a patch... hint hint :)

**Comment by nickman** [comment]
That could be ugly if you configure max-num-tags to a value lower that the actual max number of tags in hbase. Could you store the max in hbase somewhere and then check when OpenTSDB connects. It would allow higher, but not lower.

**Comment by jtamplin** [comment]
On Mon, Feb 2, 2015 at 2:34 PM, kylemallory <notifications@github.com>
wrote:

> First, of all, there needs to be some kind of error or other indication
> when attempting to write a metric with more than 8 tags. Currently (based
> on my log level), tsdb quietly drops the metric, and I'm left wondering why
> my metric isn't showing up in the database.
>
> Secondly, could MAX_NUM_TAGS become a configurable/tunable item? I have a
> few metrics which are pushing the tag limit. I understand the performance
> reasons/concerns associated with changing this, but would rather not have
> to recompile/deploy everytime I tweak this value.
>
This controls the number of bytes used to identify tags, so if you change
it the existing data becomes unusable.  Conceivably, we could change the
encoding to say how many bits are being used, but that wastes a lot of bits
in HBase on things that are largely static.  Another option which might
waste fewer bits is to have some schema version id in the row key which
then was looked up in a table to get the sizes.  However, I'm not sold on
this being all that useful to support changing it without modifying old
data.

-- 
John A. Tamplin

**Comment by oozie** [comment]
I agree that for the reasons @jtamplin pointed out, `MAX_NUM_TAGS` should not be configurable. It would create a world of supportability problems.

**Comment by kylemallory** [comment]
I understand the reasoning behind invalidating the schema if this value changes, and that it wouldn't be helpful for anyone.  That said, I disgree that is should not be configurable.  I think we need to find a way, per @jtamplin, of tying that part of the configuration to the schema.  There need not be a lot of overhead required, reading once at TSD startup from the HBase schema.  And have the max-num-tags configured/written to the schema when the schema is first created, which, honestly, openTSDB should be doing as part of its initial configuration.

This would actually be a benefit going forward, in upgrade scenarios.  IMO, As it is now, if I modify MAX_NUM_TAGS to support my environment, building a schema to match that, and then someone else 6 months or a year later, upgrades to a new release and fails to increase the MAX_NUM_TAGS again, you'll have an even larger "support problem" world in trying to figure out why the schema is broken.

I would actually be happy to try and address a solution for this; but while I've got a shit-ton of experience in Java, I have sub-zero experience in Hadoop/HBase/etc; so I might need a little hand-holding and copious peer review.  ;-)

**Comment by jtamplin** [comment]
On Mon, Mar 23, 2015 at 12:13 PM, Kyle Mallory <notifications@github.com>
wrote:

> I understand the reasoning behind invalidating the schema if this value
> changes, and that it wouldn't be helpful for anyone. That said, I disgree
> that is should not be configurable. I think we need to find a way, per
> @jtamplin <https://github.com/jtamplin>, of tying that part of the
> configuration to the schema. There need not be a lot of overhead required,
> reading once at TSD startup from the HBase schema. And have the
> max-num-tags configured/written to the schema when the schema is first
> created, which, honestly, openTSDB should be doing as part of its initial
> configuration.
>
The problem is the overhead is additional storage for every single row in
HBase.  Even if you make it a single byte, that is not an insignificant
cost.

> This would actually be a benefit going forward, in upgrade scenarios. IMO,
> As it is now, if I modify MAX_NUM_TAGS to support my environment, building
> a schema to match that, and then someone else 6 months or a year later,
> upgrades to a new release and fails to increase the MAX_NUM_TAGS again,
> you'll have an even larger "support problem" world in trying to figure out
> why the schema is broken.
>
If you mean not actually supporting mixed tag lengths in a DB (which still
means wiping all old data if you change it) but just recording the
information used for the DB, I would be fine with that.

-- 
John A. Tamplin

**Comment by manolama** [comment]
``MAX_NUM_TAGS`` doesn't affect the schema at all, it's just an arbitrary setting to prevent users from accidentally sending in time series with insane cardinality and tag combos. This can be changed at any time, up or down, without affecting any existing data.

The ``METRICS | TAG_NAME | TAG_VALUE_WIDTH`` are the static variables that affect the # of bytes UIDs are using in the DB. These can't be changed with a DB rewrite and trying to support a mixture of lengths isn't possible without some nasty hackery. But, since some folks have asked, we could make those configurable and check the UID table on startup to make sure it's still compatible and not allow the TSD to start if it's changed.

**Comment by bobrik** [comment]
@manolama will you accept a PR with `tsd.core.max_num_tags` config parameter instead of `MAX_NUM_TAGS` class constant? We'd like to use official packages instead of building patched distribution.

**Comment by mlosapio** [comment]
So this creates an interesting dilemma when using an HTTP batch post method to upload metrics. In the event a specific metric has more than 8 tags, the entire batched HTTP request fails. This isn't 1:1 with the  telnet-like interface (which effectively silently fails).

**Comment by dprime** [comment]
This thread appears to present contradictory information. I also have a scenario where I'd *really* like to use 9 or 10 tags for a certain metric but have to make do with 8. The two ideas put forward here are that changing MAX_NUM_TAGS in core/Const.java does not actually affect the schema and is perfectly safe to do, but may have performance impacts. There is also the view that increasing this number will fundamentally change how data is stored and stop an opentsdb configured with MAX_NUM_TAGS=8 from reading/writing data in a schema written by an opentsdb with MAX_NUM_TAGS!=8.

Which of these is correct?

**Comment by johann8384** [comment]
This is addressed with the "tsd.storage.max_tags" parameter.

https://github.com/OpenTSDB/opentsdb/blob/master/src/core/TSDB.java#L167
