### ISSUE TITLE
Authentication / access control to openTSDB writes - any plans

### ISSUE THREAD

**Issue by kkossack** [OpenTSDB/opentsdb#501]
Is there a recommended mechanism for authentication of tcollector writes to openTSDB?  Is support planned?  Thanks.

**Comment by manolama** [comment]
No plans yet. If you or anyone would volunteer to code it I'd be happy to coordinate :)

**Comment by johann8384** [comment]
I've been thinking about this and my thought was to implement secure RPC plugins to replace the default telnet RPC plugin and HTTP rpc plugin. 

For Telnet, I thought that we could use STARTTLS support that Netty has and then peform authentication once we've encrypted. There are probably better ways though. I haven't tried anything yet.

The Auth would be pluggable with a really basic default plugin available. The framework would need to support Kerberos like the rest of the eco-system, LDAP/AD, and probably SAML or something. I probably won't be implementing all that, but the framework should be flexible enough to allow *someone* to implement each of those.

**Comment by IDerr** [comment]
Hey, great work, but one question, why only on writes and not on read ?

**Comment by johann8384** [comment]
We'll technically, it would be applied to any HTTP or Telnet protocol connection, so read requests are subject to the authentication protocol also. It is handled by Netty prior to handing the connection off to the RPC manager.

**Comment by IDerr** [comment]
Ok, thanks for the explanation.

**Comment by IDerr** [comment]
One more thing, why not use kerberos for auth ? Like Hadoop services :) 

Thanks for your work

**Comment by johann8384** [comment]
Well, mostly because I really don't know how to do implement that and it seemed like a better use of time to implement an authentication interface whereby others can implement the authentication schemes that fit their needs.

Feel free to implement the plugin for that! :) I would be happy to assist in testing that code as well as tweaking the plugin interface if we uncover any shortcomings. I'm certain that the interface may need adjustments as folks try to actually use it. I implemented a very rudimentary plugin just to demonstrate this interface.

**Comment by johann8384** [comment]
I've started work on an authentication plugin and some hooks in the code which will delegate "should I allow this" to whatever authentication plugin is registered.

 See #1060 for future reference.
