### ISSUE TITLE
"tsdb fsck" doesn't know AppendDataPoints

### ISSUE THREAD

**Issue by Dieken** [OpenTSDB/opentsdb#640]
When enable_appends=true,  TSDB writes HBase column "\x05\x00\x00" (See src/core/AppendDataPoints.java),  src/tools/Fsck doesn't know how to handle this, it warns:

 386           LOG.warn("Found an object possibly from a future version of OpenTSDB\n\t"                                                                                                                           
 387               + kv);

**Comment by Dieken** [comment]
During investigation of this warning, I thought about a performance issue,  no matter it's compacted, not compacted or single appended column,  TSDB has to read all columns of a single row to get data point for recent time range in an hour(*is this right?*).

So, suppose 4 bytes column qualifier and 8 bytes value,  a new data point every 10s,  and Grafana automatically refreshes.  When it is near the end of an hour, even for the most efficient AppendDataPoints, it's (3600s/10s * (4 bytes + 8 bytes)) ~= 4.2 KB，that means  (QPS * num_metrics_on_dashboard * 4.2)KB/s read in from HBase and written out to Grafana even the user needs just data points in recent 15min.  I feel it's a little wasteful.

**Comment by manolama** [comment]
Ah good catch, I forgot to add the append handling. I'll get that done here shortly.

Re: the efficiency, it is a little wasteful for requests where we need tip data but, since Grafana refreshes the entire range already anyway, it doesn't make too much of a difference. If we tweaked Grafana (or other dashboards) to re-load just the tip then we could try adding filters on individual columns and fetch less. However for individual columns, we get an extra 4 bytes with each column for the timestamp plus, depending on the store files (I think) you have the rowkey duplicated. So appends help cut down on that a fair amount.

**Comment by manolama** [comment]
Fixed in 7db3bb8803e5e11cdc1690e9ad84069543269653
