### ISSUE TITLE
Downsampling question

### ISSUE THREAD

**Issue by youzhagui2006** [OpenTSDB/opentsdb#808]
why  Downsampling want to align time?

**Comment by johann8384** [comment]
Well, downsampling is going to have to align the times in order to downsample. I assume you mean why does it try to fix it to even minutes/hours/days?

That functionality was added in PR #657.

There is a configuration parameter which controls whether or not it is active: 

tsd.query.downsample.use_calendar

**Comment by IDerr** [comment]
I think @johann8384 has resolved this, and no answer has been made by @youzhagui2006,
so you can close this :)

**Comment by IDerr** [comment]
@manolama

**Comment by youzhagui2006** [comment]
in 2.3  you can 
downsampling:avg-all  solve this problem

**Comment by youzhagui2006** [comment]
@IDerr  in 2.3 you can
downsampling:avg-all solve this problem

**Comment by IDerr** [comment]
Ok, thanks for the feedback.
