### ISSUE TITLE
Information on salting

### ISSUE THREAD

**Issue by rcastbergw** [OpenTSDB/opentsdb#874]
Hi,

Could somebody shed a bit of light on salting and how that affects how many rows get used in hbase.
I have tried playing around with the salt width and salt buckets, but have been unable to find what is best for distributing the data as much as possible.

In 2.2-rc3 we even saw a decreasing number of rows  with increasing salt width as we imported data to opentsdb. While 2.3-rc1 it only increased when we went up to a salt width of 3.

**Comment by manolama** [comment]
Well the distribution of rows depends on the cardinality of a given metric.

For example, lets assume you have the following:
* 20 region servers
* 20 salt buckets
* Salt width of 1
* You pre-split the ``tsdb`` table into 20 regions based on the salt ID (i.e. the first byte).

Lets say your metric is: ``system.cpu.user`` and the only tag is ``host``.

If you have 1 host that you're monitoring, you'll only write to a 1 region server and you'll only see a single row every hour.

Now if you have 10 hosts, you'll likely write to 10 different region servers and see 10 rows per hour.

At 20 hosts you should hopefully be hitting all of the region servers. It still depends on the Java hashing algo which will take the combination of the metric and tags to generate the hash with a modulus on the number of buckets.

So Salt width has little to do with the distribution, and it should almost always be left at ``1``. Instead, set the salt bucket count to some factor of the number of region servers you have (or plan to have) but don't pick something too large (because each query creates a scanner for each salt bucket). We have about 120 region servers and find that a bucket size of 20 is perfectly good for us.

Hope that helps a bit.

**Comment by rcastbergw** [comment]
Thanks for your answer, i will have to play around with the parameters and splits in hbase.

**Comment by HariSekhon** [comment]
@manolama Thanks for this explanation.

This aligns with what I thought from reading docs - I've used opentsdb salting originally using the same number of buckets as regions in order to try to get a better balance across a pre-split HBase table (both for performance and to avoid issues #867 and #878), similar to what you'd described above, but had to increase the number of buckets and pre-split regions to prevent overloading some regions / regionservers during bulk importing, I believe due to collisions from the smaller bucket space.

Some follow up questions I have on your example above:

1. Using only 20 buckets and 20 regions despite having 120 region servers - will that not limit the data distribution to only 20 regions and fail to utilise all the region servers, at least initially?

2. Regarding the salt width - the number of buckets would seem fixed by modulus so the salt width doesn't really help unless you need > 256 buckets?

**Comment by manolama** [comment]
HI @HariSekhon, happy to help :)

1) Yes, so you actually would want to initially pre-split those 20 regions into more regions, e.g. 120 regions per bucket, so a good pre-split in this case would be a total of 2400 regions.

2) Right again. The configurable width is really there for future proofing in case we find the need to increase salting beyond a byte while at the same time finding a query method that wouldn't require 256+ simultaneous scans.

**Comment by HariSekhon** [comment]
@manolama 

I'm conscious that splitting to too many regions may cause read performance issues from all the extra read scanners.

In our case I don't think extra splitting beyond the first salt byte would help anyway as I wrote a tool to determine the distribution of metric + tag combinations in the opentsdb input files and it was heavily skewed to just a few unique combinations out of 50M data points (you can find the tool opentsdb_calculate_import_metric_distribution.py in my [PyTools repo](https://github.com/harisekhon/pytools) along with a few other HBase tools).

From what I understand of the salting mechanism the low cardinality of keys would result in the same salt prefix per key anyway which helps against monotonically incrementing surrogate UIDs but can't split the low cardinality to higher cardinality so splitting the ranges even more wouldn't really help.

**Comment by yaduvendrachoubey** [comment]
@manolama I have a small cluster with 5 region servers. Without salting most of the data is writing to one hbase region server which is causing very bad read performance when issuing multiple queries at the same time. 
Could you please advise if salting will help in this case. If yes then what should be the bucket size as i have only 5 region servers.
Im using multiple tags (5) in the metrics format.

**Comment by IDerr** [comment]
Hi @rcastbergw
if your question has been answered can you close this issue please ?

Thanks
