### ISSUE TITLE
Real-time metadata not working

### ISSUE THREAD

**Issue by iondulgheru** [OpenTSDB/opentsdb#916]
Hi there
Let me say first that I am using 2.3.0RC1.
The issue that I have is that metadata is not updated in real-time, but only when I run the metasync (tsdb uid metasync). But this command takes a whole day to run.
The config has:
tsd.core.meta.enable_realtime_ts = true
We need this in order to use Grafana dynamic templating

Here is the entire config
{  
   "tsd.core.auto_create_metrics":"true",
   "tsd.core.auto_create_tagks":"true",
   "tsd.core.auto_create_tagvs":"true",
   "tsd.core.connections.limit":"0",
   "tsd.core.meta.cache.enable":"false",
   "tsd.core.meta.enable_realtime_ts":"true",
   "tsd.core.meta.enable_realtime_uid":"false",
   "tsd.core.meta.enable_tsuid_incrementing":"false",
   "tsd.core.meta.enable_tsuid_tracking":"false",
   "tsd.core.plugin_path":"",
   "tsd.core.preload_uid_cache":"false",
   "tsd.core.preload_uid_cache.max_entries":"300000",
   "tsd.core.socket.timeout":"0",
   "tsd.core.stats_with_port":"false",
   "tsd.core.storage_exception_handler.enable":"false",
   "tsd.core.tree.enable_processing":"false",
   "tsd.core.uid.random_metrics":"false",
   "tsd.http.cachedir":"/tmp/opentsdb",
   "tsd.http.query.allow_delete":"false",
   "tsd.http.request.cors_domains":"*",
   "tsd.http.request.cors_headers":"Authorization, Content-Type, Accept, Origin, User-Agent, DNT, Cache-Control, X-Mx-ReqToken, Keep-Alive, X-Requested-With, If-Modified-Since",
   "tsd.http.request.enable_chunked":"true",
   "tsd.http.request.max_chunk":"65536",
   "tsd.http.show_stack_trace":"true",
   "tsd.http.staticroot":"/home/hadoop/opentsdb/share/opentsdb/static/",
   "tsd.mode":"rw",
   "tsd.network.async_io":"true",
   "tsd.network.bind":"0.0.0.0",
   "tsd.network.keep_alive":"true",
   "tsd.network.port":"4242",
   "tsd.network.reuse_address":"true",
   "tsd.network.tcp_no_delay":"true",
   "tsd.network.worker_threads":"",
   "tsd.no_diediedie":"true",
   "tsd.query.allow_simultaneous_duplicates":"true",
   "tsd.query.enable_fuzzy_filter":"true",
   "tsd.query.filter.expansion_limit":"4096",
   "tsd.query.skip_unresolved_tagvs":"false",
   "tsd.query.timeout":"0",
   "tsd.rtpublisher.enable":"false",
   "tsd.rtpublisher.plugin":"",
   "tsd.search.enable":"false",
   "tsd.search.plugin":"",
   "tsd.startup.enable":"false",
   "tsd.startup.plugin":"",
   "tsd.stats.canonical":"false",
   "tsd.storage.compaction.flush_interval":"10",
   "tsd.storage.compaction.flush_speed":"2",
   "tsd.storage.compaction.max_concurrent_flushes":"10000",
   "tsd.storage.compaction.min_flush_threshold":"100",
   "tsd.storage.enable_appends":"false",
   "tsd.storage.enable_compaction":"true",
   "tsd.storage.fix_duplicates":"true",
   "tsd.storage.flush_interval":"1000",
   "tsd.storage.hbase.data_table":"tsdb",
   "tsd.storage.hbase.meta_table":"tsdb-meta",
   "tsd.storage.hbase.prefetch_meta":"false",
   "tsd.storage.hbase.scanner.maxNumRows":"128",
   "tsd.storage.hbase.tree_table":"tsdb-tree",
   "tsd.storage.hbase.uid_table":"tsdb-uid",
   "tsd.storage.hbase.zk_basedir":"/hbase",
   "tsd.storage.hbase.zk_quorum":"head1.int.xxxxx.com,head2.int.xxxxx.com,data1.int.xxxxx.com,data2.xxxxx.com,data3.int.xxxxx.com:2181",
   "tsd.storage.repair_appends":"false",
   "tsd.timeseriesfilter.enable":"false",
   "tsd.uidfilter.enable":"false"
}
}

Is something wrong in my config?

Thank you

**Comment by iondulgheru** [comment]
After also adding to the config tsd.core.meta.enable_tsuid_tracking = true, the metadata was created real-time.
But the documentation specifies that only tsd.core.meta.enable_realtime_ts = true is needed in order to create the metadata without running "tsdb uid metasync"

**Comment by manolama** [comment]
Ah, sorry for the confusion. I updated the docs at http://opentsdb.net/docs/build/html/user_guide/metadata.html.

**Comment by larsf** [comment]
I have a similar issue, but adding tsd.core.meta.enable_tsuid_tracking = true and running tsdb uid metasync didn't make a difference.

These are the options that I think are related to metadata that we enable:
tsd.core.auto_create_metrics = true
tsd.core.meta.enable_realtime_ts = true
tsd.core.meta.enable_tsuid_tracking = true

This query returns an empty result:

http://192.168.1.1:4242/api/search/lookup?limit=3000&m=cpu.percent{fqdn=*}

{
"type": "LOOKUP",
"metric": "cpu.percent",
"tags": [
{
"key": "fqdn",
"value": "*"
}
],
"limit": 3000,
"time": 2,
"results": [ ],
"startIndex": 0,
"totalResults": 0
}

while this query shows that cpu.percent does contain the fqdn tag:
http://192.168.1.1:4242/api/query?start=1m-ago&m=sum:cpu.percent{fqdn=*}
[
{
"metric": "cpu.percent",
"tags": {
"fqdn": "node91.my.lab"
},
"aggregateTags": [
"cpu_class",
"cpu_core"
],
"dps": {
"1485123431": 399.99999380111694,
"1485123441": 399.99999663978815,
"1485123451": 399.9999994635582,
"1485123461": 399.99999901652336,
"1485123471": 399.999996997416,
"1485123481": 399.99999940395355
}
},....

This issue is preventing the template variables from being loaded on dashboard load. our query for the fqdn variable is: tag_values(cpu.percent,fqdn), which translates into the first query mentioned above..
