### ISSUE TITLE
Allow opentsdb to take advantage of DateTieredCompaction

### ISSUE THREAD

**Issue by churrodog** [OpenTSDB/opentsdb#962]
DateTieredCompaction uses the scan's TimeRange to exclude store files for scanning.  This is very helpful when doing reads from timeseries data.  The problem is that it looks to be that opentsdb uses the key range to specify the query (which is great), but can we also pass along a timerange as well?  This would allow us to use this compaction strategy with opentsdb.   I assume the user can specify an Error, which is how long after we send the request that it gets persisted to hbase.  That way our TimeRange query will include a buffer of this error on both sides of our time range scan.  I can put up a patch for this if those are interested.

**Comment by churrodog** [comment]
any interest in getting this feature out?  I have found significant I/O improvement because we don't have to constantly re-compact the same files over and over from using Date Tiered Compaction

**Comment by manolama** [comment]
Yeah we have some other companies who want to put in some work to implement this. If you could submit your PR that'd be a great starting point for this. Thanks!

**Comment by alienth** [comment]
DateTieredCompaction has been deprecated in the latest stable cassandra. Preferred solution nowadays is TimeWindowCompactionStrategy, which is provides similar functionality.

Not sure why you'd need any tsdb code changes - the queries you'd run against cass are identical regardless of using normal compaction or DTCS/TWCS.

**Comment by churrodog** [comment]
that is not true, the timestamp is stored in the row key and qualifier not
in the cell's timestamp, and the tsdb query never passes TimeRange to the
scan. The whole idea is to skip a lot of store files when doing the scan by
using timerange to exclude many windows up front.

The rowkey is metric,timestamp.  If your metric spans every window and you
only want data in the most recent window you won't be able to do that
correctly because if you use the cell timestamp it does not match the
metric timestamp in most cases and will not include data in the query it
should, thus you have to either give some error bound to each query for a
timerange or have the cell timestamp match the metric timestamp.

**Comment by alienth** [comment]
Ah, my mistake, I thought you were referring to DTCS in Cassandra.

**Comment by karanmehta93** [comment]
(Copying this comment from [PR #971 ](https://github.com/OpenTSDB/opentsdb/pull/971) for further discussion.
A potential issue with this patch that we should decide as to how it should be handled.

If we write a integer value followed by a float value on the same metric timestamp, currently OpenTSDB would filter out the earlier entries of data by using the cell timestamps. Although we only maintain 1 version per timestamp, but column qualifiers with a float and integer values will be different, even with the same time offsets. This process of filtering out old values is carried out during compaction. I believe that this is the reason as to why we run compaction whenever query#run() is called.

After the patch, since we write the metric timestamp as cell timestamp, writes done for the same timestamp will have the same cell timestamp but will have different column qualifiers. Hence there is no way to determine the correct value of metric at that point since we cannot differentiate between them.

Can anyone suggest ideas for handling this scenario?
How often are we to encounter such cases in practical cases? Is it fine if we can eliminate them or leave up to the code to return any value?
Currently we have support for selecting either the oldest or the latest value, which is configurable.

I feel that this patch would require doing changes in the way OpenTSDB stores data in HBase.
